### ISSUE TITLE
Fakereplace transforming classes not part of the package specified in parameters

### ISSUE THREAD

**Issue by themustafarian** [fakereplace/fakereplace#11]
I'm trying to use fakereplace with Jboss7 to hot deploy my application classes while doing development. I added the following to my jvm arguments in eclipse:

-javaagent:/usr/local/lib/fakereplace.jar=packages=com.myapp

when I start jboss I see many exceptions in the console like this:

 [org.fakereplace.manip.MethodInvokationManipulator] ERROR Bad byte code transforming com.mysql.jdbc.ConnectionImpl
 org.fakereplace.javassist.bytecode.BadBytecode: stack underflow at 418 
   at org.fakereplace.javassist.bytecode.CodeAnalyzer.visitBytecode(CodeAnalyzer.java:86)
   at org.fakereplace.javassist.bytecode.CodeAnalyzer.computeMaxStack(CodeAnalyzer.java:50)
   at org.fakereplace.javassist.bytecode.CodeAttribute.computeMaxStack(CodeAttribute.java:239)
   at org.fakereplace.manip.MethodInvokationManipulator.transformClass(MethodInvokationManipulator.java:158)
   at org.fakereplace.manip.Manipulator.transformClass(Manipulator.java:112)
   at org.fakereplace.core.Transformer.transform(Transformer.java:116)

Which seems to mean that fakereplace is trying to transform classes that are not in com.myapp.

Is my understanding of this behavior wrong?

Am also getting the following exception when I want to build my project in eclipse:

org.eclipse.jpt.jpa.core.internal.jpa1.context.java.GenericJavaEmbeddedIdMapping cannot be cast to org.eclipse.jpt.jpa.core.context.RelationshipMapping

Hence, my attempt to tell fakereplace to only replace specific classes.

Thanks for your help.

**Comment by fbricon** [comment]
@stuartwdouglas I think this one was fixed with https://github.com/fakereplace/fakereplace/commit/92732dfa70a366602c4a41c4503b8587f9ff186e
