### ISSUE TITLE
Fail to start zipkin-enabled wildfly-swarm app

### ISSUE THREAD

**Issue by fbricon** [fakereplace/fakereplace#17]
I'm starting the org.wildfly.swarm.Swarm main class on a wildfly-swarm app (https://github.com/redhat-helloworld-msa/hola) from Eclipse, adding the fakereplace agent. The app fails to start with:

```
objc[70384]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Fakereplace listening on port 6555
Dependencies not bundled, will resolve from local M2REPO
[0m09:40:51,195 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
[0m[0m09:40:51,804 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: WildFly Core 2.0.10.Final "Kenny" starting
[0m2016-09-09 09:40:53,267 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 17) WFLYSEC0002: Activating Security Subsystem
2016-09-09 09:40:53,277 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 15) WFLYIO001: Worker 'default' has auto-configured to 8 core threads with 64 task threads based on your 4 available processors
2016-09-09 09:40:53,278 INFO  [org.jboss.as.security] (MSC service thread 1-7) WFLYSEC0001: Current PicketBox version=4.9.4.Final
2016-09-09 09:40:53,289 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0003: Undertow 1.3.15.Final starting
2016-09-09 09:40:53,292 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 14) WFLYUT0003: Undertow 1.3.15.Final starting
2016-09-09 09:40:53,352 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 21) WFLYNAM0001: Activating Naming Subsystem
2016-09-09 09:40:53,353 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 22) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
2016-09-09 09:40:53,428 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
2016-09-09 09:40:53,484 INFO  [org.xnio] (MSC service thread 1-6) XNIO version 3.3.4.Final
2016-09-09 09:40:53,548 INFO  [org.xnio.nio] (MSC service thread 1-6) XNIO NIO Implementation Version 3.3.4.Final
2016-09-09 09:40:53,698 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-6) WFLYUT0012: Started server default-server.
2016-09-09 09:40:54,268 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.0.10.Final "Kenny" started in 3878ms - Started 83 of 95 services (18 services are lazy, passive or on-demand)
2016-09-09 09:40:54,381 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
2016-09-09 09:40:59,383 INFO  [org.wildfly.swarm.runtime.deployer] (main) deploying b520276a-2bad-4e76-968f-7ab70a5de048.war
2016-09-09 09:40:59,429 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0027: Starting deployment of "b520276a-2bad-4e76-968f-7ab70a5de048.war" (runtime-name: "b520276a-2bad-4e76-968f-7ab70a5de048.war")
2016-09-09 09:41:02,019 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-3) WFLYSRV0018: Deployment "deployment.b520276a-2bad-4e76-968f-7ab70a5de048.war" is using a private module ("org.jboss.jts:main") which may be changed or removed in future versions without notice.
2016-09-09 09:41:02,134 INFO  [org.jboss.weld.deployer] (MSC service thread 1-2) WFLYWELD0003: Processing weld deployment b520276a-2bad-4e76-968f-7ab70a5de048.war
2016-09-09 09:41:02,291 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-2) HV000001: Hibernate Validator 5.2.3.Final
2016-09-09 09:41:02,605 INFO  [stdout] (MSC service thread 1-2) null
2016-09-09 09:41:02,606 INFO  [stdout] (MSC service thread 1-2) null
2016-09-09 09:41:02,607 INFO  [stdout] (MSC service thread 1-2) null
2016-09-09 09:41:02,615 INFO  [org.apache.deltaspike.core.util.ProjectStageProducer] (MSC service thread 1-2) Computed the following DeltaSpike ProjectStage: Production
2016-09-09 09:41:02,615 INFO  [stdout] (MSC service thread 1-2) null
2016-09-09 09:41:02,616 INFO  [stdout] (MSC service thread 1-2) null
2016-09-09 09:41:02,798 INFO  [org.jboss.weld.deployer] (MSC service thread 1-5) WFLYWELD0006: Starting Services for CDI deployment: b520276a-2bad-4e76-968f-7ab70a5de048.war
2016-09-09 09:41:02,900 INFO  [org.jboss.weld.Version] (MSC service thread 1-5) WELD-000900: 2.3.2 (Final)
2016-09-09 09:41:02,996 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0018: Host default-host starting
2016-09-09 09:41:03,026 INFO  [org.jboss.weld.deployer] (MSC service thread 1-7) WFLYWELD0009: Starting weld service for deployment b520276a-2bad-4e76-968f-7ab70a5de048.war
2016-09-09 09:41:03,529 INFO  [org.jboss.weld.Event] (MSC service thread 1-8) WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-09-09 09:41:03,636 INFO  [org.jboss.weld.Event] (MSC service thread 1-8) WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-09-09 09:41:03,644 INFO  [org.jboss.weld.Event] (MSC service thread 1-8) WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-09-09 09:41:03,911 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:03,924 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:03,924 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:03,926 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:03,926 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:03,936 INFO  [stdout] (MSC service thread 1-8) null
2016-09-09 09:41:04,556 WARN  [org.jboss.weld.Validator] (MSC service thread 1-8) WELD-001478: Interceptor class org.apache.deltaspike.core.impl.throttling.ThrottledInterceptor is enabled for the application and for the bean archive b520276a-2bad-4e76-968f-7ab70a5de048.war/WEB-INF/lib/deltaspike-core-impl-1.6.1.jar. It will only be invoked in the @Priority part of the chain.
2016-09-09 09:41:04,556 WARN  [org.jboss.weld.Validator] (MSC service thread 1-8) WELD-001478: Interceptor class org.apache.deltaspike.core.impl.lock.LockedInterceptor is enabled for the application and for the bean archive b520276a-2bad-4e76-968f-7ab70a5de048.war/WEB-INF/lib/deltaspike-core-impl-1.6.1.jar. It will only be invoked in the @Priority part of the chain.
2016-09-09 09:41:04,556 WARN  [org.jboss.weld.Validator] (MSC service thread 1-8) WELD-001478: Interceptor class org.apache.deltaspike.core.impl.future.FutureableInterceptor is enabled for the application and for the bean archive b520276a-2bad-4e76-968f-7ab70a5de048.war/WEB-INF/lib/deltaspike-core-impl-1.6.1.jar. It will only be invoked in the @Priority part of the chain.
2016-09-09 09:41:05,726 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 4) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:231)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
	at io.undertow.servlet.core.ManagedListener.start(ManagedListener.java:50)
	at io.undertow.servlet.core.ApplicationListeners.start(ApplicationListeners.java:159)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:173)
	... 8 more
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:134)
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
	at org.jboss.as.ee.component.ComponentRegistry$ComponentManagedReferenceFactory.getReference(ComponentRegistry.java:149)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$6.createInstance(UndertowDeploymentInfoService.java:1366)
	at io.undertow.servlet.core.ManagedListener.start(ManagedListener.java:48)
	... 10 more
Caused by: javax.enterprise.inject.CreationException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:96)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:99)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:181)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:378)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:389)
	at org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:71)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
	at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:73)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)
	at org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
	at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	... 15 more
Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Field.______REDEFINED_METHOD_DELEGATOR_$(I[Ljava/lang/Object;)Ljava/lang/Object;
	at zipkin.internal.moshi.ClassFactory.get(ClassFactory.java:63)
	at zipkin.internal.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:62)
	at zipkin.internal.moshi.Moshi.adapter(Moshi.java:94)
	at zipkin.internal.moshi.Moshi.adapter(Moshi.java:61)
	at zipkin.internal.JsonCodec.<clinit>(JsonCodec.java:122)
	at zipkin.Codec.<clinit>(Codec.java:25)
	at com.github.kristofa.brave.internal.DefaultSpanCodec.<clinit>(DefaultSpanCodec.java:14)
	at com.twitter.zipkin.gen.SpanCodec.<clinit>(SpanCodec.java:7)
	at com.github.kristofa.brave.http.HttpSpanCollector.<init>(HttpSpanCollector.java:87)
	at com.github.kristofa.brave.http.HttpSpanCollector.create(HttpSpanCollector.java:71)
	at com.redhat.developers.msa.hola.ZipkinResource.getBrave(ZipkinResource.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	... 50 more

2016-09-09 09:41:05,731 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed - address: (("deployment" => "b520276a-2bad-4e76-968f-7ab70a5de048.war")) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.enterprise.inject.CreationException
    Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Field.______REDEFINED_METHOD_DELEGATOR_$(I[Ljava/lang/Object;)Ljava/lang/Object;"}}
2016-09-09 09:41:05,733 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "b520276a-2bad-4e76-968f-7ab70a5de048.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.enterprise.inject.CreationException
    Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Field.______REDEFINED_METHOD_DELEGATOR_$(I[Ljava/lang/Object;)Ljava/lang/Object;"}}
2016-09-09 09:41:05,757 INFO  [org.jboss.weld.deployer] (MSC service thread 1-7) WFLYWELD0010: Stopping weld service for deployment b520276a-2bad-4e76-968f-7ab70a5de048.war
2016-09-09 09:41:05,786 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0019: Host default-host stopping
2016-09-09 09:41:05,835 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment b520276a-2bad-4e76-968f-7ab70a5de048.war (runtime-name: b520276a-2bad-4e76-968f-7ab70a5de048.war) in 100ms
2016-09-09 09:41:05,837 INFO  [org.jboss.as.controller] (main) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."com.redhat.developers.msa.hola.HystrixServlet".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."com.redhat.developers.msa.hola.SwaggerListener".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."com.redhat.developers.msa.hola.ZipKinFilter".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."org.jboss.weld.servlet.WeldInitialListener".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".component."org.jboss.weld.servlet.WeldTerminalListener".START (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
      service jboss.undertow.deployment.default-server.default-host./ (missing) dependents: [service jboss.deployment.unit."b520276a-2bad-4e76-968f-7ab70a5de048.war".deploymentCompleteService] 
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./

2016-09-09 09:41:05,841 ERROR [stderr] (main) Exception in thread "main" org.wildfly.swarm.container.DeploymentException: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
2016-09-09 09:41:05,841 ERROR [stderr] (main)     Caused by: java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
2016-09-09 09:41:05,841 ERROR [stderr] (main)     Caused by: javax.servlet.ServletException: UT010013: Could not instantiate com.redhat.developers.msa.hola.ZipKinFilter
2016-09-09 09:41:05,841 ERROR [stderr] (main)     Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
2016-09-09 09:41:05,841 ERROR [stderr] (main)     Caused by: javax.enterprise.inject.CreationException
2016-09-09 09:41:05,841 ERROR [stderr] (main)     Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Field.______REDEFINED_METHOD_DELEGATOR_$(I[Ljava/lang/Object;)Ljava/lang/Object;"}}
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:159)
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.deploy(Container.java:432)
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:122)
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:45)
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.deploy(Container.java:416)
2016-09-09 09:41:05,842 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:117)
2016-09-09 09:41:05,843 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:45)
2016-09-09 09:41:05,843 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:150)
2016-09-09 09:41:05,843 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:141)

```

**Comment by fbricon** [comment]
I reckon it might be a zipkin problem though

**Comment by fbricon** [comment]
So that particular problem goes away when I update the [version of brave.jar](https://github.com/redhat-helloworld-msa/hola/blob/master/pom.xml#L61) to 3.10.0 (cc @rafabene). 

But then,  swagger fails next, or more precisely org.reflections:
```
Caused by: java.lang.NoSuchMethodError: java.util.Stack.______REDEFINED_METHOD_DELEGATOR_$(I[Ljava/lang/Object;)Ljava/lang/Object;
	at org.reflections.vfs.SystemDir$1$1.<init>(SystemDir.java:41)
	at org.reflections.vfs.SystemDir$1.iterator(SystemDir.java:39)
	at org.reflections.Reflections.scan(Reflections.java:240)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:256)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:221)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
	at com.redhat.developers.msa.hola.SwaggerListener.contextInitialized(SwaggerListener.java:41)
```
unfortunately, there's no newer version than 0.9.10, so I'm kinda stuck.

Still, I'm wandering if fakereplace shouldn't just ignore JDK classes from instrumentation altogether. Not sure we can easily detect a class belongs to the JDK anyway.

**Comment by fbricon** [comment]
I guess one alternative for me would be to collect all the package names to instrument

**Comment by stuartwdouglas** [comment]
This is a bug that I introduced as part of my changes yesterday, I have a fix for the error that you are seeing, however there appears to be another javassist bug where it is not calculating the StackMapTableAttribute correctly. I should be able to work around it though and I will hopefully have a fix early next week

**Comment by fbricon** [comment]
Good to know. I thought I'd be able to work around it by setting the packages list, but even with that, the JDK classes are instrumented.

```
-Xbootclasspath/a:"/Users/fbricon/Dev/eclipses/jee-neon/Eclipse.app/Contents/Eclipse/../../../../../projects/wildfly-hive/org.jboss.tools.servers.wildfly.swarm.core/extras/fakereplace-dist-1.0.0.Alpha3-SNAPSHOT.jar" -javaagent:"/Users/fbricon/Dev/eclipses/jee-neon/Eclipse.app/Contents/Eclipse/../../../../../projects/wildfly-hive/org.jboss.tools.servers.wildfly.swarm.core/extras/fakereplace-dist-1.0.0.Alpha3-SNAPSHOT.jar=packages=com.redhat.developers.msa.hola,port=6555,"

```

**Comment by stuartwdouglas** [comment]
When it is running under wildfly it actually ignores the packages list, as it can automatically tell which are deployment classes. It should be fixed now, however your example still fails for me (although it fails in the same way without fakereplace).

**Comment by stuartwdouglas** [comment]
Looks like I just had to set ZIPKIN_SERVER_URL, it appears to work now.
