### ISSUE TITLE
Exception logged when starting a Vert.x application

### ISSUE THREAD

**Issue by fbricon** [fakereplace/fakereplace#19]
When starting https://github.com/redhat-helloworld-msa/aloha with the latest Fakereplace from source, the following exception is logged: 

```
Fakereplace listening on port 6555
java.lang.RuntimeException: org.fakereplace.javassist.bytecode.BadBytecode: <clinit> ()V in org.apache.commons.logging.impl.Log4JLogger: failed to resolve types
	at org.fakereplace.transformation.MainTransformer.transform(MainTransformer.java:178)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:998)
	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.apache.commons.configuration.SystemConfiguration.<clinit>(SystemConfiguration.java:35)
	at com.netflix.config.ConfigurationManager.getConfigInstance(ConfigurationManager.java:127)
	at com.netflix.config.DynamicPropertyFactory.getInstance(DynamicPropertyFactory.java:263)
	at com.github.kennedyoliveira.hystrix.contrib.vertx.metricsstream.EventMetricsStreamHandler.<clinit>(EventMetricsStreamHandler.java:56)
	at com.redhat.developers.msa.aloha.AlohaVerticle.start(AlohaVerticle.java:84)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$163(DeploymentManager.java:429)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.fakereplace.javassist.bytecode.BadBytecode: <clinit> ()V in org.apache.commons.logging.impl.Log4JLogger: failed to resolve types
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:111)
	at org.fakereplace.javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:440)
	at org.fakereplace.transformation.MainTransformer.transform(MainTransformer.java:173)
	... 34 more
Caused by: org.fakereplace.javassist.bytecode.BadBytecode: failed to resolve types
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:169)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	... 36 more
Caused by: org.fakereplace.javassist.NotFoundException: org.apache.log4j.Priority
	at org.fakereplace.javassist.ClassPool.get(ClassPool.java:452)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.fixTypes2(TypeData.java:345)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.fixTypes(TypeData.java:330)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.dfs(TypeData.java:274)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.fixTypes(MapMaker.java:390)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:167)
	... 37 more
Service running at 0.0.0.0:8080
```
Method replacement appears to work as expected though, which is nice, but that stacktrace seems a bit scary.

PS: We might need to add specific Vert.x support in the future, to restart changed Verticles for instance, but that's an entirely different topic (@vietj or @cescoffier might be interested into looking into it)

**Comment by fbricon** [comment]
Apparently, the problem may be caused by Log4J missing from the runtime classpath, being an optional dependency.

**Comment by cescoffier** [comment]
Hi @fbricon yes to don't provide log4j as a transitive dependency as it depends whether or not the app is using log4j, log4j2, slf4j, jul .... So we don't ship any ;-).

**Comment by stuartwdouglas** [comment]
This should be a fairly easy fix. Basically JDK8 requires a stupid StackMapTableAttribute that now requires you to have access to the complete class hierarchy of lots of types at runtime when invoking a method. 

In this case the method will fail with NoClassDefFoundError anyway, so if building the stack map fails I will just rewrite the method to throw NoClassDefFoundError directly.
