### ISSUE TITLE
Hot deployment fails on WildFly 18.0 / Windows

### ISSUE THREAD

**Issue by initshdb** [fakereplace/fakereplace#38]
Hi,

Working on windows Wildfly 18, I deployed my-app.war in Wildfly (not exploded) and did this change  in standalone.conf.bat 

`set "JAVA_OPTS=%JAVA_OPTS% -javaagent:C:/Users/myuser/fakereplace/dist/target/fakereplace.jar=index-file=C:/Users/myuser/fakereplace/dist/target/fakereplace.index,server,log=debug,packages=com.myapp.view -Dfakereplace.source-paths.lera-beta.war=C:/Users/myuser/my-app/src/main/java"`

Fakereplace is able to detect a change in the source file MyAppView.java, but WildFly fails to load the changes, with this error, 
`Exception handling request to /my-app/: java.lang.NoClassDefFoundError: Failed to link com\myapp\view\MyAppView (Module "deployment.my-app.war" from Service Module Loader): com\myapp\view\MyAppView (wrong name: com/myapp/view/MyAppView)`
What could be happening?

```
2020-06-20 02:03:46,907 INFO  [stdout] (default task-3) Fakereplace detected the following source files have been changed: [com\myapp\view\MyAppView]

020-06-20 02:03:47,376 WARN  [org.jboss.modules.define] (default task-3) Failed to define class com\myapp\view\MyAppView in Module "deployment.my-app.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link com\myapp\view\MyAppView (Module "deployment.my-app.war" from Service Module Loader): com\myapp\view\MyAppView (wrong name: com/myapp/view/MyAppView)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.fakereplace.integration.wildfly.autoupdate.WildflyAutoUpdate.runUpdate(WildflyAutoUpdate.java:118)
	at org.fakereplace.integration.wildfly.autoupdate.WebUpdateHandlerWrapper$WebUpdateHandler.handleRequest(WebUpdateHandlerWrapper.java:75)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)

2020-06-20 02:03:47,382 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /my-app/: java.lang.NoClassDefFoundError: Failed to link com\myapp\view\MyAppView (Module "deployment.my-app.war" from Service Module Loader): com\myapp\view\MyAppView (wrong name: com/myapp/view/MyAppView)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.fakereplace.integration.wildfly.autoupdate.WildflyAutoUpdate.runUpdate(WildflyAutoUpdate.java:118)
	at org.fakereplace.integration.wildfly.autoupdate.WebUpdateHandlerWrapper$WebUpdateHandler.handleRequest(WebUpdateHandlerWrapper.java:75)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
```

I will very much appreciate any help.

Thanks, Nitish

**Comment by stuartwdouglas** [comment]
Fakereplace is not really actively maintained any more, I am too busy working on Quarkus.

**Comment by initshdb** [comment]
Thank you @stuartwdouglas for the quick response. I understand that Fakerplace is not be worked upon, however, I think that the issue I face above is something that should be working with the existing Fakereplace, maybe it is just something to do with the usage or WildFly configuration. If you can quickly glance through the error details you might understand what I could be doing wrong. I'd highly appreciate,

**Comment by initshdb** [comment]
Just an update, with help from a #31, I was able to resolve the issue cause. The issue was due to file separator expected as "/" in `WildFlyAutoUpdate.java`, as below
`classDefinition[i] = new ClassDefinition(classLoader.loadClass(className.replace("/", ".")), compiler.getOutput().get(className).toByteArray());`
changed ` / ` to `File.separator`
`classDefinition[i] = new ClassDefinition(classLoader.loadClass(className.replace(File.separator, ".")), compiler.getOutput().get(className).toByteArray());`

I will close the issue.
Thank You @stuartwdouglas for this awesome library, it is of help to me and my team :)

**Comment by initshdb** [comment]
@stuartwdouglas just one question, does Fakereplace also reloads xhtml in JSFs? With my configuration as `packages=com.myapp.view ` and `fakereplace.source-paths.lera-beta.war=C:/Users/myuser/my-app/src/main/java` it only reloads java classes. Can, in the existing Fakereplace, we configure to reload changes to xhtml in src/main/webapp?
Your response would be highly appreciated.

**Comment by stuartwdouglas** [comment]
If you create a file WEB-INF/undertow-external-mounts.conf and add a line in it pointing to your src/main/webapp dir this might do it.

**Comment by stuartwdouglas** [comment]
This is not a Fakereplace thing, but a WildFly one.

**Comment by initshdb** [comment]
This worked!
I am so grateful to you for your help @stuartwdouglas, and for this library.
But why have you stopped work actively on Fakereplace? It does a great job and many have benefitted too, so why this is no longer maintained or worked up?

**Comment by stuartwdouglas** [comment]
I just don't have time, most of my time is spent working on Quarkus now,
and Fakereplace never really took off.

Stuart
