### ISSUE TITLE
agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c

### ISSUE THREAD

**Issue by rahuldjha** [fakereplace/fakereplace#44]
I obtained the most recent release from https://mvnrepository.com/artifact/org.fakereplace/fakereplace-dist and added it to the agent path to JBOSS Server JAVA_OPTS.
export JAVA_OPTS="${JAVA_OPTS} -javaagent:C:/JBoss/fakereplace-dist-1.0.0.Alpha7.jar=server,log=debug";
Then I added the Maven plugin from https://mvnrepository.com/artifact/org.fakereplace/fakereplace-maven-plugin/1.0.0.Alpha5 to the pom.xml of the project which I want to deploy. After building the project now when I am trying to start the server, I am getting the below exception:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NoClassDefFoundError: org/fakereplace/core/ClassLookupManager
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.fakereplace.core.Fakereplace.premain(Fakereplace.java:96)
        ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

**Comment by VibhaIV** [comment]
Any solution for the issue?
