### ISSUE TITLE
Java 7 issue on osx 

### ISSUE THREAD

**Issue by sjhorn** [fakereplace/fakereplace#5]
After running with the following command:

```
java -cp bin -javaagent:/Users/shorn/dev/fakereplace-1.0.0.Alpha2/fakereplace.jar=packages=com.hornmicro com.hornmicro.HelloWorldReload
```
on:

```
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)
```

I receive the following error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:88)
	at org.fakereplace.core.Agent.premain(Agent.java:93)
	... 6 more
```

**Comment by stuartwdouglas** [comment]
This was fixed a while ago
