### ISSUE TITLE
Support for JBoss 7.2.0 / EAP 6.1.0

### ISSUE THREAD

**Issue by dzwicker** [fakereplace/fakereplace#8]
We use the jboss 7.2.0 and we setup the agent we got a lot of org.fakereplace.javassist.bytecode.BadBytecode starting with e.g.:

```
org.fakereplace.javassist.bytecode.BadBytecode: readConfiguration (Ljava/io/InputStream;)V in org.jboss.logmanager.LogManager: failed to resolve types
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:110)
	at org.fakereplace.javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:423)
	at org.fakereplace.manip.Manipulator.transformClass(Manipulator.java:122)
	at org.fakereplace.core.Transformer.transform(Transformer.java:117)
	at org.fakereplace.transformation.MainTransformer.transform(MainTransformer.java:121)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:338)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:402)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:254)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:73)
	at org.jboss.modules.Module.loadModuleClass(Module.java:518)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:182)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
	at java.util.logging.LogManager$1.run(LogManager.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:176)
	at org.jboss.modules.Main.main(Main.java:313)
Caused by: org.fakereplace.javassist.bytecode.BadBytecode: failed to resolve types
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:167)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:107)
	... 23 more
Caused by: org.fakereplace.javassist.NotFoundException: org.jboss.logmanager.Configurator
	at org.fakereplace.javassist.ClassPool.get(ClassPool.java:450)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.fixTypes2(TypeData.java:340)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.fixTypes(TypeData.java:325)
	at org.fakereplace.javassist.bytecode.stackmap.TypeData$TypeVar.dfs(TypeData.java:270)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.fixTypes(MapMaker.java:315)
	at org.fakereplace.javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:165)
	... 24 more
```

I have changed the dependencies for the project to hit the version used by jboss 7.2 and found that WritableServiceBasedNamingStore has changed in jboss 7.2 so there is an error in JBossASHibernate4ClassChangeAware:93....

I have attached the full log as start.jpg ;-) as txt is not supported.
![start](https://f.cloud.github.com/assets/500483/667252/7bbb4b66-d7ec-11e2-8bcd-3800152417d3.jpg)

Perhaps you could give any advice where to start with these errors to fix them.

**Comment by stuartwdouglas** [comment]
This was fixed a while ago
